name: Test
on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Configure Zig compiler
        uses: mlugg/setup-zig@v2
        with:
          use-cache: false
      - name: Test
        run: zig build test
