name: Test
on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v7
      - name: Configure Zig compiler
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.16.0
      - name: Test
        run: zig build test
